name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Fw2020/**'
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          brew install libsass
          make test

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          docker run -v `pwd`:`pwd` -w `pwd` --name j2 --rm swift:5.5 /bin/bash -c "apt-get update; apt-get install libsqlite3-dev libsass0 libsass-dev; make test"
