name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Fw2020/**'
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-14

    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          brew install libsass
          make test

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          docker run -v `pwd`:`pwd` -w `pwd` --name j2 --rm swift:5.10 /bin/bash -c "apt-get update; apt-get install make libsqlite3-dev libsass1 libsass-dev; make test"
