name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Fw2020/**'
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          brew install libsass
          make test

          #  linux:
          #name: Linux SPM unit tests
          #runs-on: ubuntu-latest
    
          #steps:
          #- uses: actions/checkout@v1
          #- name: Run tests
          #run: |
          #docker run -v `pwd`:`pwd` -w `pwd` --name j2 --rm swift:5.8 /bin/bash -c "apt-get update; apt-get install libsqlite3-dev libsass0 libsass-dev; make test"
