name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Fw2020/**'
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run tests
        run: |
          brew install libsass
          make test

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tools
        run: apt-get update && apt-get install make libsqlite3-dev libsass1 libsass-dev
      - name: Build
        run: swift build
          #      - name: Test
          #        run: swift test
